---
functional:
- Пользователь должен иметь возможность зарегистрироваться
- Пользователь должен иметь возможность восстановить пароль
- Пользователь должен иметь возможность авторизоваться
- Пользователь должен иметь возможность авторизоваться с использованием аккаунта Github
- Пользователь должен иметь возможность авторизоваться с использованием аккаунта Discord
- Пользователь должен иметь возможность начать игру с ботом
- Пользователь должен иметь возможность начать игру с реальным пользователем
- Пользователь должен иметь возможность видеть код соперника в реальном времени
- Пользователь должен иметь возможность быть в качестве зрителя в запущенной игре
- Пользователь должен иметь возможность следить за открытыми играми без посещения сайта, с помощью расширения для Chrome
non-functional:
- Сайт должен быть разработан с учетом удобства использования
- Сайт должен быть оптимизирован для скорости работы
- Сайт должен быть безопасным и защищать данные пользователя
- Сайт должен быть удобным на мобильном устройстве
- Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
