---
functional:
- Пользователь должен иметь возможность зарегистрироваться
- Пользователь должен иметь возможность авторизоваться с использованием почты
- Пользователь должен иметь возможность восстановить пароль
- Пользователь должен иметь возможность авторизоваться с использованием аккаунта Github, Discord 
- Пользователь должен иметь возможность начать игру с ботом
- Пользователь должен иметь возможность начать игру с другим реальным пользователем
- Пользователь должен иметь возможность начать игру с другом
- Пользователь должен видеть код соперника в реальном времени
- Пользователь должен иметь возможность быть в качестве зрителя в запущенной игре
- Пользователь должен иметь возможность выбрать игру по уровню сложности
- Пользователь должен иметь возможность выбрать конкретную игру
- Пользователь должен иметь возможность менять язык программирования во время решения
- Задачи должны быть даны русском и английском языках
- Зарегистрированные пользователи должны иметь возможность общаться в чате
- Завершенная игра доступна в записи
- Пользователи получают очки, на основе которых строятся рейтинги за неделю, месяц, всё время
non-functional:
- Сайт должен быть разработан с учетом удобства использования
- Сайт должен быть оптимизирован для скорости работы
- Сайт должен быть безопасным и защищать данные пользователя
- Сайт должен быть удобным на мобильном устройстве
- Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
- Пользователь должен иметь возможность просматривать свой профиль
- Пользователь должен иметь возможность менять информацию о себе
- Пользователь должен иметь возможность менять настройки звука
- Пользователь может привязать аккаунты Github и Discord в настройках
- Пользователь должен иметь возможность создавать новое задание
- Плашка "Codebattle by Hexlet's community" должна перенаправлять на главный экран
- Пользователь должен иметь возможность начать игру с другим реальным пользователем по ссылке
- Пользователь должен иметь возможность следить за открытыми играми без посещения сайта, с помощью расширения для Chrome